basePath: /rederinghub.io/v1
definitions:
  request.GenerateMessageRequest:
    properties:
      address:
        type: string
    type: object
  request.UpdateProfileRequest:
    properties:
      bio:
        type: string
      display_name:
        type: string
    type: object
  request.VerifyMessageRequest:
    properties:
      address:
        type: string
      signature:
        type: string
    type: object
  response.GeneratedMessage:
    properties:
      message:
        type: string
    type: object
  response.JsonResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/response.RespondErr'
      status:
        type: boolean
    type: object
  response.LogoutResponse:
    properties:
      message:
        type: string
    type: object
  response.ProfileResponse:
    properties:
      avatar:
        type: string
      bio:
        type: string
      created_at:
        type: string
      display_name:
        type: string
      id:
        type: string
      wallet_address:
        type: string
    type: object
  response.RespondErr:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.VerifyResponse:
    properties:
      access_token:
        type: string
      is_verified:
        type: boolean
      refresh_token:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server Autonomous devices management server.
  title: 'Autonomous: OG Device APIs server.'
  version: 1.0.0
paths:
  /auth/nonce:
    post:
      consumes:
      - application/json
      description: Generate a message for user's wallet
      parameters:
      - description: Generate message request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.GenerateMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.GeneratedMessage'
              type: object
      summary: Generate a message
      tags:
      - Auth
  /auth/nonce/verify:
    post:
      consumes:
      - application/json
      description: Verified the generated message
      parameters:
      - description: Verify message request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.VerifyMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VerifyResponse'
              type: object
      summary: Verified the generated message
      tags:
      - Auth
  /profile:
    get:
      consumes:
      - application/json
      description: User profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ProfileResponse'
              type: object
      security:
      - Authorization: []
      summary: User profile
      tags:
      - Profile
    put:
      consumes:
      - application/json
      description: Edit User profile
      parameters:
      - description: Update profile request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ProfileResponse'
              type: object
      security:
      - Authorization: []
      summary: Edit User profile
      tags:
      - Profile
  /profile/logout:
    post:
      consumes:
      - application/json
      description: Logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.LogoutResponse'
              type: object
      security:
      - Authorization: []
      summary: Logout
      tags:
      - Profile
  /token/{contractAddress}/{tokenID}:
    get:
      consumes:
      - application/json
      description: get token uri data
      parameters:
      - description: contract address
        in: path
        name: contractAddress
        required: true
        type: string
      - description: token ID
        in: path
        name: tokenID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.GeneratedMessage'
              type: object
      summary: get token uri data
      tags:
      - token_uri
securityDefinitions:
  Api-Key:
    in: header
    name: Api-Key
    type: apiKey
  Authorization:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
