// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: boilerplate.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetGenerativeBoilerplateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGenerativeBoilerplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGenerativeBoilerplateRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetGenerativeBoilerplateRequestMultiError, or nil if none found.
func (m *GetGenerativeBoilerplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGenerativeBoilerplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetGenerativeBoilerplateRequestMultiError(errors)
	}

	return nil
}

// GetGenerativeBoilerplateRequestMultiError is an error wrapping multiple
// validation errors returned by GetGenerativeBoilerplateRequest.ValidateAll()
// if the designated constraints aren't met.
type GetGenerativeBoilerplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGenerativeBoilerplateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGenerativeBoilerplateRequestMultiError) AllErrors() []error { return m }

// GetGenerativeBoilerplateRequestValidationError is the validation error
// returned by GetGenerativeBoilerplateRequest.Validate if the designated
// constraints aren't met.
type GetGenerativeBoilerplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGenerativeBoilerplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGenerativeBoilerplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGenerativeBoilerplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGenerativeBoilerplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGenerativeBoilerplateRequestValidationError) ErrorName() string {
	return "GetGenerativeBoilerplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetGenerativeBoilerplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGenerativeBoilerplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGenerativeBoilerplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGenerativeBoilerplateRequestValidationError{}

// Validate checks the field values on GetGenerativeBoilerplateResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetGenerativeBoilerplateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGenerativeBoilerplateResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetGenerativeBoilerplateResponseMultiError, or nil if none found.
func (m *GetGenerativeBoilerplateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGenerativeBoilerplateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetGenerativeBoilerplateResponseMultiError(errors)
	}

	return nil
}

// GetGenerativeBoilerplateResponseMultiError is an error wrapping multiple
// validation errors returned by
// GetGenerativeBoilerplateResponse.ValidateAll() if the designated
// constraints aren't met.
type GetGenerativeBoilerplateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGenerativeBoilerplateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGenerativeBoilerplateResponseMultiError) AllErrors() []error { return m }

// GetGenerativeBoilerplateResponseValidationError is the validation error
// returned by GetGenerativeBoilerplateResponse.Validate if the designated
// constraints aren't met.
type GetGenerativeBoilerplateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGenerativeBoilerplateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGenerativeBoilerplateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGenerativeBoilerplateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGenerativeBoilerplateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGenerativeBoilerplateResponseValidationError) ErrorName() string {
	return "GetGenerativeBoilerplateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetGenerativeBoilerplateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGenerativeBoilerplateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGenerativeBoilerplateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGenerativeBoilerplateResponseValidationError{}
