// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: token.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetTokenMessageReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTokenMessageReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTokenMessageReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTokenMessageReqMultiError, or nil if none found.
func (m *GetTokenMessageReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTokenMessageReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ContractAddr

	// no validation rules for TokenId

	if len(errors) > 0 {
		return GetTokenMessageReqMultiError(errors)
	}

	return nil
}

// GetTokenMessageReqMultiError is an error wrapping multiple validation errors
// returned by GetTokenMessageReq.ValidateAll() if the designated constraints
// aren't met.
type GetTokenMessageReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTokenMessageReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTokenMessageReqMultiError) AllErrors() []error { return m }

// GetTokenMessageReqValidationError is the validation error returned by
// GetTokenMessageReq.Validate if the designated constraints aren't met.
type GetTokenMessageReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTokenMessageReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTokenMessageReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTokenMessageReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTokenMessageReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTokenMessageReqValidationError) ErrorName() string {
	return "GetTokenMessageReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetTokenMessageReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTokenMessageReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTokenMessageReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTokenMessageReqValidationError{}

// Validate checks the field values on GetTokenMessageResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTokenMessageResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTokenMessageResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTokenMessageRespMultiError, or nil if none found.
func (m *GetTokenMessageResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTokenMessageResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetTokenMessageRespMultiError(errors)
	}

	return nil
}

// GetTokenMessageRespMultiError is an error wrapping multiple validation
// errors returned by GetTokenMessageResp.ValidateAll() if the designated
// constraints aren't met.
type GetTokenMessageRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTokenMessageRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTokenMessageRespMultiError) AllErrors() []error { return m }

// GetTokenMessageRespValidationError is the validation error returned by
// GetTokenMessageResp.Validate if the designated constraints aren't met.
type GetTokenMessageRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTokenMessageRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTokenMessageRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTokenMessageRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTokenMessageRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTokenMessageRespValidationError) ErrorName() string {
	return "GetTokenMessageRespValidationError"
}

// Error satisfies the builtin error interface
func (e GetTokenMessageRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTokenMessageResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTokenMessageRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTokenMessageRespValidationError{}
